   Algoritmo "Medidas"

   Var
   A, B, C, quadrado, triangulo, trapezio: real

   Inicio

   escreva ("Digite a medida A: ")
   leia (A)
   escreva ("Digite a medida B: ")
   leia (B)
   escreva ("Digite a medida C: ")
   leia (C)
   
        quadrado <- A^2
        triangulo <- (A*B)/2
        trapezio <- ((A+B)*C)/2

   escreval ("Área do quadrado = ", quadrado:8:4)
   escreval ("Área do trangulo = ", triangulo:8:4)
   escreval ("Área do trapezio = ", trapezio:8:4)
   Fimalgoritmo
